name: Configuration split
type: module
description: Configuration filter for importing and exporting split config
# core: 8.x
package: Other
configure: entity.config_split.collection

# Information added by Drupal.org packaging script on 2017-02-10
version: '8.x-1.0-beta2'
core: '8.x'
project: 'config_split'
datestamp: 1486720689
