# Local development services.
#
# To activate this feature, follow the instructions at the top of the
# 'example.settings.local.php' file, which sits next to this file.
parameters:
  #http.response.debug_cacheability_headers: true

services:
 # config.storage.sync:
  #  class: Drupal\config_split\Config\StorageWrapper
   # factory: config_split.manager:getDefaultStorageWrapper